#!/bin/bash

echo "Setting up docker repository..."

sudo apt-get update

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
	
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
   
echo "Installing docker..."   
   
sudo apt-get update

sudo apt-get install docker-ce

echo "Docker installed."

echo "Downloading probcomp stack"

wget https://probcomp-1.csail.mit.edu/probcomp-stack/probcomp-stack-full-0.3.1.tar.gz

sudo docker load --input probcomp-stack-full-0.3.1.tar.gz

sudo apt-get install -f python-pip

pip install bayeslite
